### ISSUE TITLE
双击放大缩小成功率太低了，都是直接变成点击的手势

### ISSUE THREAD

**Issue by CoderPby** [gsdios/SDPhotoBrowser#20]
如题，希望能修复一下

**Comment by CoderPby** [comment]
还有，能不能把状态栏也给隐藏了，微信微博等都是没有状态栏的，感谢

**Comment by ChenMengqi** [comment]
第一个次进browser里的时候，的确是每次双击只能被识别到单次点击，要是图片放大过或者缩小过，双击放大是有效果的。

我比较不理解的是 为什么double tap要加在self和image view两个地方？如果去掉self里的那个手势，就不会有LS提出的这个bug了，只是因为单击手势要等双击手势识别失败，稍微有点延迟，解决办法也是有的，StackOverflow上有。  继承个新的tap gesture或者 重写touch event

@gsdios

**Comment by gsdios** [comment]
已经修复，请下载最新代码测试下，感谢关注与支持！
